### ISSUE TITLE
Vue Object Syntax

### ISSUE THREAD

**Issue by aklinker1** [anime-skip/player#127]
https://github.com/orgs/anime-skip/projects/4#card-44645288

`common/components`

- [x] AutocompleteTextInput (#128)
- [x] Checkbox (#122)
- [x] Loading (#123)
- [x] PlaybackRatePicker (#126)
- [x] ProgressOverlay (#123)
- [x] TextInput (#130)
- [x] WebExtImg (#129)

`common/mixins`

- [x] KeyboardShortcuts (#132)
- [x] VideoController (#132)

`player`

- [x] AnimatedIcon (#131)
- [x] FullscreenButton (#131)
- [x] PlayPauseButton (#131)
- [x] VolumeButton (#132)
- [x] EditTimestamp (#132)
- [x] EpisodeInfo (#132)
- [x] BasicDialog (#138)
- [x] Section (#134)
- [x] Timeline (#135)
- [x] TimestampDetails (#132)
- [x] Toolbar (#132)
- [x] ToolbarButton (#134)
- [x] AccountDialog (#134)
- [x] TimestampsPanel (#132)
- [x] Player (#136)

`popup`

- [x] Login (#133)
- [x] PopupHeader (#133)
- [x] Preferences (#133)
- [x] Popup (#133)

Other

- [x] Delete Vuex decorators (#138)
- [x] Remove class packages (#138)
- [x] Remove useless getters (#138)
