### ISSUE TITLE
Extract Player UI into separate package

### ISSUE THREAD

**Issue by aklinker1** [anime-skip/player#260]
### Summary

In order to reuse the player UI as part of the embedded player, I need to pull it out into it's own package first.

There's a couple problems with how the code is currently setup; the main one being that the player UI is tightly coupled with the browser extension APIs.

### Todos

- [x] ~~_Abstract away the `browser.storage` APIs_~~ #257 
- [x] ~~_Don't load icons from URLs_~~ #259 
- [x] ~~_Don't send messages from inside the player (global search for "new Messenger")_~~ #261 
- [x] ~~_Taking a screenshot should be as simple as a function passed via config_~~ #261 
- [ ] Move player component and utils to the `packages/player-ui` directory
