### ISSUE TITLE
Alpha 4 Bugs

### ISSUE THREAD

**Issue by aklinker1** [anime-skip/player#92]
- [x] ~~When editing, if you edit the episode info then cancel, it stops editing and you lose all the timestamps you made~~
  - The "edit episode info" button is now hidden when editing
- [x] ~~When you select the same show from autocomplete, it clears all the episode info~~
  - Created own issue to tackle this one #102
- [x] ~~When you press edit timestamps, only pause when opening the edit episode dialog~~
  - This is no longer an issue since there is no "Edit" button until there are episode details
- [x] Double check that creating a show and episode hides the dialog correctly after it is done
- [x] Inferring of episode info does not work first time (or something, it's inconsistent) (Fixed in #103)
- [x] Use a form so that enter submits episode info on the edit episode dialog (Fixed in #104)
- [x] Unknown timestamps can't be deleted (Fixed by #100)
- [x] Inject for all of the website (Fixed by #99)
- [x] If there is inferred data for a few fields, and the episode is saved without values for those fields, the inferred data shows up (Fixed by #101)
